export const MENU_NAME_SELECTED = 'MENU_NAME_SELECTED'

/*article mutation*/
export const SET_ARTICLE = 'SET_ARTICLE'

export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE'

export const SET_ARTICLE_TAGS = 'SET_ARTICLE_TAGS'

export const SET_ARTICLE_CONTENT = 'SET_ARTICLE_CONTENT'

export const SET_ARTICLE_ISPUBLISHED = 'SET_ARTICLE_ISPUBLISHED'

export const QUERY_ARTICLE_BY_ID = 'QUERY_ARTICLE_BY_ID'

//export const UPDATE_ARTICLE_BY_ID = 'UPDATE_ARTICLE_BY_ID'

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'