export const MENU_NAME_SELECTED = 'MENU_NAME_SELECTED'

export const MENU_DISPLAY_TOGGLE = 'MENU_DISPLAY_TOGGLE'

/*article mutation*/
export const SET_ARTICLE = 'SET_ARTICLE'

export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE'

export const SET_ARTICLE_INTRO = 'SET_ARTICLE_INTRO'

export const SET_ARTICLE_TAGS = 'SET_ARTICLE_TAGS'

export const SET_ARTICLE_LIKES = 'SET_ARTICLE_LIKES'

export const SET_ARTICLE_VIEWS = 'SET_ARTICLE_VIEWS'

export const SET_ARTICLE_CONTENT = 'SET_ARTICLE_CONTENT'

export const SET_ARTICLE_ISPUBLISHED = 'SET_ARTICLE_ISPUBLISHED'

export const QUERY_ARTICLE_BY_ID = 'QUERY_ARTICLE_BY_ID'

export const SET_ARTICLE_TYPE = 'SET_ARTICLE_TYPE'

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'

export const SET_ARTICLE_ISRECOMMEND = 'SET_ARTICLE_RECOMMEND'

export const SET_ARTICLE_THUMBURL = 'SET_ARTICLE_THUMBURL'

export const SET_ARTICLE_UNIQUEMARK = 'SET_ARTICLE_UNIQUEMARK'


/*tags mutation*/
export const SET_TAG_COLORT = 'SET_TAG_COLORT'

export const SET_TAG_LIST = 'SET_TAG_LIST'


/*types mutation*/
export const SET_TYPE_LIST = 'SET_TYPE_LIST'

export const GET_TYPE_LIST = 'GET_TYPE_LIST'

