export const MENU_NAME_SELECTED = 'MENU_NAME_SELECTED'

/*article mutation*/
export const SET_ARTICLE = 'SET_ARTICLE'

export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE'

export const SET_ARTICLE_TAGS = 'SET_ARTICLE_TAGS'

export const SET_ARTICLE_CONTENT = 'SET_ARTICLE_CONTENT'

export const SET_ARTICLE_ISPUBLISHED = 'SET_ARTICLE_ISPUBLISHED'

export const SET_ARTICLE_THUMBNAIL = 'SET_ARTICLE_THUMBNAIL'

export const QUERY_ARTICLE_BY_ID = 'QUERY_ARTICLE_BY_ID'

//export const UPDATE_ARTICLE_BY_ID = 'UPDATE_ARTICLE_BY_ID'

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'




/*tags mutation*/
export const SET_TAG_COLORT = 'SET_TAG_COLORT'

export const SET_TAG_LIST = 'SET_TAG_LIST'


/*types mutation*/
export const SET_TYPE_LIST = 'SET_TYPE_LIST'
export const GET_TYPE_LIST = 'GET_TYPE_LIST'

