export const SET_CURRENT_MENU_NAME = 'SET_CURRENT_MENU_NAME'
export const MOBILE_MENU_TOGGLE = 'MOBILE_MENU_TOGGLE'
export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU'
export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU'

export const SET_ARTICLE_CATALOG = 'SET_ARTICLE_CATALOG'
export const ARTICLE_CATALOG_TOGGLE = 'ARTICLE_CATALOG_TOGGLE'

export const SET_CURRENT_ARTICLE_TYPE = 'SET_CURRENT_ARTICLE_TYPE'
export const SET_ARTICLE_TYPES = 'SET_ARTICLE_TYPES'

export const SET_ARTICLE_TAGS = 'SET_ARTICLE_TAGS'

export const INCREASE_PAGE_NUM = 'INCREASE_PAGE_NUM'
export const REDUCE_PAGE_NUM = 'REDUCE_PAGE_NUM'
export const RESET_PAGE_NUM = 'RESET_PAGE_NUM'