export const SET_CURRENT_MENU_NAME = 'SET_CURRENT_MENU_NAME'
export const MOBILE_MENU_TOGGLE = 'MOBILE_MENU_TOGGLE'
export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU'
export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU'

export const SET_ARTICLE_CATALOG = 'SET_ARTICLE_CATALOG'
export const ARTICLE_CATALOG_TOGGLE = 'ARTICLE_CATALOG_TOGGLE'